name: Scheduled Nostr Post

on:
  schedule:
    - cron: "0 */6 * * *" # 6時間ごとに実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # リポジトリのコードをチェックアウト

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Node.jsのバージョンを指定

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node develop/dist/bot.js # 実行ファイル
